services:
  - type: web
    name: autou
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        value: s8&z@e^npatsh07&s+j8o12*^_0m2sskp^_+hz%9o&zc!vvpb
      - key: DEBUG
        value: 'False'
      - key: HF_API_KEY
        value: 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
      - key: MODEL_PATH
        value: api/utils/email-classifier