name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NSCALE_SERVICE_TOKEN: ${{ secrets.NSCALE_SERVICE_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: python -m pip install --upgrade pip

      - run: pip install -r requirements.txt

      - run: docker compose -f infra/compose.yaml up -d

      - run: python manage.py migrate

      - run: docker compose -f infra/compose.yaml down

      - run: python manage.py test
